version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kursach
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"  # Порт, на котором будет доступен Nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Конфигурация Nginx
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  db_data:
